### ISSUE TITLE
(S1/S2) Link to Query API is broken at bottom of Readme.md

### ISSUE THREAD

**Issue by JetstreamRoySprowl** [Azure-Samples/Azure-Time-Series-Insights#4] opened 2018-12-20 01:57 UTC
Link to Query API is broken at bottom of [Readme.md](https://github.com/Azure-Samples/Azure-Time-Series-Insights/blob/master/C-%20Hello%20World%20App%20Sample/README.md)

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by yeskarthik** [comment] 2019-03-19 20:53
This is not possible in one call and it is by design. When you send a /events requests - Top by time ($ts), You can send the subsequent request with the adjusted searchspan - the largest timestamp you received should be the "from" timestamp of the searchspan.

**Comment by yeskarthik** [comment] 2019-03-19 20:55
Closed by mistake.

**Comment by yeskarthik** [comment] 2019-03-19 22:10
This has been fixed too.

**Closed by yeskarthik** 2019-03-19 22:10 UTC
